echo Running \"problem_1.py\"...
./problem_1.py

echo Running \"problem_2.py\"...
./problem_2.py

echo Running \"problem_3.py\"...
./problem_3.py

echo Running \"problem_4_1.py\"...
./problem_4_1.py

echo Running \"problem_4_2.py\"...
./problem_4_2.py

echo Running \"problem_4_3.py\"...
./problem_4_3.py

echo All scripts run