echo Running \"problem_1.py\"...
./problem_1.py

echo Running \"problem_2.py\"...
./problem_2.py

echo Running \"problem_3.py\"...
./problem_3.py

echo Running \"problem_4_part_1.py\"...
./problem_4_part_1.py

echo Running \"problem_4_part_2.py\"...
./problem_4_part_2.py

echo Running \"problem_4_part_3.py\"...
./problem_4_part_3.py

echo All scripts run